### ISSUE TITLE
Integration with rendering freameworks

### ISSUE THREAD

**Issue by qwelias** [WebReflection/usignal#21]
We may want to integrate it with react and possibly other rendering engines, do you have any plans or ideas on how to provide the glue for it? (e.g. `useSignal`, etc. hooks for react)

I was thinking on just copypasting what preact-signals have as a submodule here (like `usignal/solid`), but want to ask first

**Comment by WebReflection** [comment]
theoretically this API is almost a drop-in for preact signals so whatever they do should work here too ... *should* though, as I haven't seen what they do or what they have, but I am confident it should be enough. Any explicit link before I land in the wrong file around preact `useSignal` implementation?

**Comment by qwelias** [comment]
I was looking [here](https://github.com/preactjs/signals/blob/main/packages/react/src/index.ts)

The `useSignal`, `useComputed`, and `useSignalEffect` look simple enough.
The rest of that file looks confusing to me, that's what I'm not sure about, should've clarified it initially.

(I'm guessing the rest there is to be able to just pass signals into JSX and have it working automatically, if so then it's nice, but hooks should be enough imo, feel free to close in that case)

**Comment by qwelias** [comment]
> if so then it's nice, but hooks should be enough imo, feel free to close in that case

On the second thought it's not exactly clear how to make sure react rerenders the component on signal update.
Something like that I guess (if using hooks from [here](https://github.com/preactjs/signals/blob/main/packages/react/src/index.ts)):
```jsx
const sub = (signal) => {
  const [, rerender] = useState(signal.value)
  return [signal, effect(() => rerender(signal.value))]
}

const Component = () => {
  const [signal, unsub] = sub(useSignal(123))
  return <div>{signal.value}</div>
}
```

**Comment by WebReflection** [comment]
to be honest, I am not sure what is wrong with this approach, when it comes to hook based libraries:

```js
const useSignal = value => {
  const [current, update] = useState(value);
  return {
    get value() { return current },
    set value(_) { update(_) }
  };
};
``

**Comment by Mex505** [comment]
What you talking about? I keep getting this messages could you tell me
exactly what your seeing for I could understand. Please tell me in simple
words nothing fancy or this big words i dont even know what they mean.
THANK YOU

**Comment by qwelias** [comment]
In my case we may use signals created somehwere else (e.g. shared data model module, which notifies about updates through signal value), so we need to to be albe to hook a component to a signal which could be modified from somewhere else
