### ISSUE TITLE
Computed value is undefined

### ISSUE THREAD

**Issue by dy** [WebReflection/usignal#36]
@WebReflection please correct me what I do wrong or misunderstand:

```js
import { signal, computed } from "usignal";

const c = signal(0);
const d = computed(() => c.value * 2);
console.log(d.peek()); // undefined
```

[sandbox](https://codesandbox.io/p/sandbox/usignal-test-5r8qwh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsxpyylq00063b6ar9hjpxbb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsxpyylq00023b6acdv9uc8r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsxpyylq00033b6aazz8kc3i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsxpyylq00053b6a74cwih8e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsxpyylq00023b6acdv9uc8r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxpyylq00013b6ali7tlmu2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsxpyylq00023b6acdv9uc8r%2522%252C%2522activeTabId%2522%253A%2522clsxpyylq00013b6ali7tlmu2%2522%257D%252C%2522clsxpyylq00053b6a74cwih8e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxpyylq00043b6apc5fqk80%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsxpyylq00053b6a74cwih8e%2522%252C%2522activeTabId%2522%253A%2522clsxpyylq00043b6apc5fqk80%2522%257D%252C%2522clsxpyylq00033b6aazz8kc3i%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsxpyylq00033b6aazz8kc3i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

It doesn't seem to be the case with `@preact/signals-core`.

**Comment by dy** [comment]
In particular I hoped to use it in untracked function to allow sub-effects
`const untracked = fn => computed(fn).peek()`

**Comment by WebReflection** [comment]
without effects around and nobody subscribing via `.value` I don't know why you would need a computed instead of a regular `fn()` returned value but I've kinda moved to https://github.com/WebReflection/signal when reactivity is minimal and use either preact core or solid signals for more battle-tested solutions, see [uhtml/preactive](https://github.com/WebReflection/uhtml?tab=readme-ov-file#exports).

I should probably sunset this module as I don't have time, nor care much these days, about it and I won't likely fix anything in the near future.

**Comment by dy** [comment]
One use case I just showed. @webreflection/signal has the same issue. 
Main reason why I wanted to use usignal over preact-signals is the size - it's twice smaller.

Do you have and idea how can I make untracked function with usignal? In preact/signals it's exported by default.

If you prefer I can check out the source and propose a PR

**Comment by WebReflection** [comment]
PR welcome, I hope the code in `./esm/` folder is eaasy enough to follow, thanks!

**Comment by titoBouzout** [comment]
@WebReflection do you have any signals implementation that you actually maintain?

**Comment by titoBouzout** [comment]
Thanks! @dy one of the issues with all this small signal libraries is that making anything that isn't trivial requires a Context API, if they don't expose an owner, with parents and a runWithOwner it becomes impossible to implement.

**Comment by titoBouzout** [comment]
I do not use react/preact, I come from a solidjs background, see https://pota.quack.uy/

**Comment by WebReflection** [comment]
uhtml/preactive and uhtml/signal give you that parent owner if I understood your concern ... as you always need a function to render (when you want nested/confined reactivity) or skip that to render parent on changes within nested components.
