### ISSUE TITLE
Update benchmark numbers for @preact/signals-core

### ISSUE THREAD

**Issue by marvinhagemeister** [WebReflection/usignal#9]
We've just released a new version of `@preact/signals-core` where we reworked the internals. With the new version the numbers don't reflect the measurements in the readme anymore. These are the results I get on my machine (M1 Pro) with a fresh clone from usignal.

<img width="826" alt="Screenshot 2022-09-21 at 18 15 04" src="https://user-images.githubusercontent.com/1062408/191556929-7ed2e66a-9bce-449b-bc2b-b9a295bdd1a5.png">

**Comment by WebReflection** [comment]
gosh ... I've put this bench up like minutes ago ... and that's a plot-twist !!! will run again and update the image

**Comment by WebReflection** [comment]
uhm ... that doesn't sound right folks ... are you ditching subscriptions here? 'cause if I do, this is the result

![Screenshot from 2022-09-21 18-24-20](https://user-images.githubusercontent.com/85749/191559026-e83940e0-9bae-4ae5-aeed-b7763c4af047.png)

**Comment by WebReflection** [comment]
P.S. I'm not blaming your release, just trying to understand if we're comparing apples to oranges here ...

**Comment by WebReflection** [comment]
@marvinhagemeister ???

**Comment by WebReflection** [comment]
P.S. I've created a [ditching-subscriptions](https://github.com/WebReflection/usignal/tree/ditching-subscriptions) branch which passes the test and smokes 'em all.

![Screenshot from 2022-09-21 19-57-00](https://user-images.githubusercontent.com/85749/191576753-2f31f6e2-c29c-4003-8e22-8dec85bb41a2.png)

**Comment by marvinhagemeister** [comment]
No, we're not ditching subscriptions. We're only setting them up when needed.

I'm unable to reproduce the results you have on my end:

![Screenshot 2022-09-21 at 20 07 25](https://user-images.githubusercontent.com/1062408/191578850-60f5cfbe-88c3-4dbb-a07f-22554abb7724.png)

Let me know if there are more steps needed to run the benchmarks for the `ditching-subscriptions` branch.

**Comment by WebReflection** [comment]
> We're only setting them up when needed.

what does it mean? how can you know if a computed has conditional logic in it on a second run?

> I'm unable to reproduce the results you have on my end:

yeah, that was my bad, I've pushed the branch without changes in it ... please try again with the same branch, and `npm run benchmark`

**Comment by WebReflection** [comment]
P.S. I am planning to change the benchmark to use conditional logic inside, and have predictable results to verify correctness on a second run too (currently all computed just have same signals repeated times).

maybe that can show off some extra timing, or correctness, to consider ...

**Comment by WebReflection** [comment]
meanwhile ... the benchmark doesn't look for correctness, it just looks for known results ... we should review benchmarks before using these ...

**Comment by WebReflection** [comment]
OK, I've added the new screenshot after changing the demo to consider conditional subscriptions and indeed preact is correct.

I've updated the image in the README, I hope this is OK, and fair ... but I am also extremely curious to know how you managed to achieve these performance *skipping* subscriptions with some fine grain control.

If you could share a bit what happens there, it'd be awesome, otherwise I need to dig into your code.

Closing, unless you think the benchmark is still not correct.

![benchmark](https://user-images.githubusercontent.com/85749/191669356-3fdc79ae-d184-4b5d-a66b-d14da0930697.png)

**Comment by marvinhagemeister** [comment]
Thanks for updating the benchmark results. The main PR that made it possible on our side, is this one: https://github.com/preactjs/signals/pull/161/files
